### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by chuckcaley** [KimJorgensen/KungFuFlash2#1]
Not sure if it's my 64 or the KFF2. But when I load Sonic the hedgehog on my c64c the game crashes in random places. The game doesn't run more the 30 secs. It runs fine on my breadbin though. I'm going to do some more testing on a load of 64's this weekend. Will update afterwards.

**Comment by KimJorgensen** [comment]
Thanks for reporting, and let me know the results of your tests.
It may be that your C64 requires a [phi2 clock offset](https://github.com/KimJorgensen/KungFuFlash2/blob/main/firmware/README.md#diagnostic)

**Comment by chuckcaley** [comment]
Done some extra testing on about 8 different models of pal c64's including the first series 64's. No issues reported all ran fine on phi2 setting +2.
