### ISSUE TITLE
Commodore 64C problem

### ISSUE THREAD

**Issue by LouDnl** [KimJorgensen/KungFuFlash2#3]
This issue is indirectly related to
https://github.com/KimJorgensen/KungFuFlash/issues/89

Sorry in advance for bumping an old issue for another cartridge in this repo.
I seem to have a very similar issue with my Rev A but then with Kungfu Flash 2.
Kf2 works fine in other mainboards, but in the rev A only a black screen appears.
Any tips or pointers on where too start with getting it to work?
I know the cartridge works, the diagnostics menu starts a serial log over USB and I can change the timing (max 30 up and down).

**Serial log:**
![IMG-20241220-WA0033.jpg](https://github.com/user-attachments/assets/eef0dbd6-5e60-4a7e-a382-befcd2e43a06)

**Mainboard:**
![20241222_103958.jpg](https://github.com/user-attachments/assets/093a8883-4d79-482b-8d1e-ad2b430b8bb7)

**Clock:**
![IMG-20241221-WA0018.jpeg](https://github.com/user-attachments/assets/8b158227-b311-4432-b600-5fd613db6e63)

![IMG-20241221-WA0019.jpeg](https://github.com/user-attachments/assets/f5bf3841-71bf-4796-adb0-80effd20cf96)

**Video output check of black screen:**
![20241221_115953.jpg](https://github.com/user-attachments/assets/89e4a08b-6217-446c-9d22-d100a6669485)

![20241221_115936.jpg](https://github.com/user-attachments/assets/519f250a-a487-401c-9c73-4ee64dce374e)

**Magicdesk reference signal:**
![20241221_115621.jpg](https://github.com/user-attachments/assets/f9899c15-8fcd-46d4-a874-e4281478fbe5)

![20241221_115933.jpg](https://github.com/user-attachments/assets/816f1c3d-38ac-4305-9228-a0fb4540dab4)

**Comment by KimJorgensen** [comment]
It could be that your C64C requires a small positive [phi2 clock offset](https://github.com/KimJorgensen/KungFuFlash2/blob/main/firmware/README.md#diagnostic) or that there is a hardware connection issue. You could try to clean the connector on the PCB.

**Comment by LouDnl** [comment]
> It could be that your C64C requires a small positive [phi2 clock offset](https://github.com/KimJorgensen/KungFuFlash2/blob/main/firmware/README.md#diagnostic) or that there is a hardware connection issue. You could try to clean the connector on the PCB.

I have tried this from -30 up to +30 without success unfortunately. Since 30 is the max offset I have tried adjusting the max offset in your firmware which allows me more then 30, but u fortunately the offset is still maxed at 30 somewhere else.
It's not the cartridge, as another kff2 cartridge that is tested to work in a c64 has the same issue in mine.
So that leaves the motherboard cartridgeslot or the need for a larger then 30 offset I guess?

**Comment by KimJorgensen** [comment]
It is unlikely that you need a offset larger than 30. Normally an offset of one or two should fix the issue.
Maybe the expansion slot is dirty or broken. Have you tried with another cartridge like Easy Flash or Final Cartridge III?

**Comment by LouDnl** [comment]
> It is unlikely that you need a offset larger than 30. Normally an offset of one or two should fix the issue.
> Maybe the expansion slot is dirty or broken. Have you tried with another cartridge like Easy Flash or Final Cartridge III?

Atm I only have 2 MagicDesk cartridges besides kff2 and they work fine.

**Comment by LouDnl** [comment]
Issue found and fixed, wasn't kff2 related in the end. It turned out to be a trace on the underside of the pcb that got damaged when replacing the old RF module with a replacement one.
This trace was for Read/Write, kind of important I recon 🤣
![IMG-20241228-WA0014.jpg](https://github.com/user-attachments/assets/967507e2-28f6-430e-8266-8d39a57f7701)

![IMG-20241228-WA0012.jpg](https://github.com/user-attachments/assets/d322c3c2-014c-41a2-aab6-11ff3949fc60)

**Comment by KimJorgensen** [comment]
Great! I'll close this issue
